#include "basis.cpp"
#include "basis_test.cpp"
#include "bessel_i.cpp"
#include "commutator.cpp"
#include "diagonal_terms.cpp"
#include "expression.cpp"
#include "fourier_transform.cpp"
#include "framework.h"
#include "index.cpp"
#include "indexed_hash_set.cpp"
#include "linear_operator.cpp"
#include "model.cpp"
#include "normal_order.cpp"
#include "operator.cpp"
#include "schriffer_wolff.cpp"
#include "static_vector.cpp"
#include "term.cpp"

int main() { return run_all_tests(); }
