#include "algebra/test_basis.cpp"
#include "algebra/test_commutator.cpp"
#include "algebra/test_expression.cpp"
#include "algebra/test_fourier_transform.cpp"
#include "algebra/test_model.cpp"
#include "algebra/test_normal_order.cpp"
#include "algebra/test_operator.cpp"
#include "algebra/test_term.cpp"
#include "algorithms/test_diagonal_terms.cpp"
#include "algorithms/test_schriffer_wolff.cpp"
#include "algorithms/test_wegner_flow.cpp"
#include "framework.h"
#include "numerics/test_lanczos.cpp"
#include "numerics/test_linear_operator.cpp"
#include "utils/test_bessel_i.cpp"
#include "utils/test_index.cpp"
#include "utils/test_indexed_hash_set.cpp"
#include "utils/test_static_vector.cpp"

int main() { return run_all_tests(); }
