#include "algebra/basis.cpp"
#include "algebra/basis_test.cpp"
#include "algebra/commutator.cpp"
#include "algebra/expression.cpp"
#include "algebra/fourier_transform.cpp"
#include "algebra/model.cpp"
#include "algebra/normal_order.cpp"
#include "algebra/operator.cpp"
#include "algebra/term.cpp"
#include "algorithms/diagonal_terms.cpp"
#include "algorithms/schriffer_wolff.cpp"
#include "algorithms/wegner_flow.cpp"
#include "framework.h"
#include "numerics/lanczos.cpp"
#include "numerics/linear_operator.cpp"
#include "utils/bessel_i.cpp"
#include "utils/index.cpp"
#include "utils/indexed_hash_set.cpp"
#include "utils/static_vector.cpp"

int main() { return run_all_tests(); }
